// ladder-tables.js -- assemble ladder tables from named eval runs.
//
//   node 03_train/lab/cli/ladder-tables.js --runs <dir>,<dir>,... [--out <dir>]
//
// Reads each run's summary.json (and its manifest for provenance), refuses
// mixed seed sets or mixed game counts (a ladder row is only comparable to
// another if both sat the same paper), and writes ladder.md and ladder.json
// to --out. Purely mechanical: tabulation, no judgement; the judgement lives
// in the campaign SUMMARY.md beside the output.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

import { round } from '../metrics.js';
import { parseArgs } from './args.js';

const args = parseArgs();
if (!args.runs) {
  console.error('usage: node 03_train/lab/cli/ladder-tables.js --runs <dir>,<dir>,... [--out <dir>]');
  process.exit(1);
}

const rows = [];
for (const dir of String(args.runs).split(',').filter(Boolean)) {
  const summary = JSON.parse(readFileSync(path.join(dir, 'summary.json'), 'utf8'));
  const manifest = JSON.parse(readFileSync(path.join(dir, 'manifest.json'), 'utf8'));
  rows.push({
    agent: summary.agent,
    describe: manifest.agent.describe,
    runId: summary.runId,
    seedSet: summary.seedSet,
    games: summary.games,
    score: summary.score,
    blocksPlaced: summary.blocksPlaced,
    longestChain: summary.longestChain,
    maxTile: summary.maxTile,
    mergeCounts: summary.mergeCounts,
    bestGame: summary.bestGame,
  });
}

const seedSets = new Set(rows.map((r) => r.seedSet));
const gameCounts = new Set(rows.map((r) => r.games));
if (seedSets.size !== 1 || gameCounts.size !== 1) {
  throw new Error(`refusing a mixed ladder: seed sets ${[...seedSets]}, game counts ${[...gameCounts]}`);
}
rows.sort((a, b) => b.score.median - a.score.median);

const fmt = (n) => (n === null || n === undefined ? 'n/a' : Number(n).toLocaleString('en-GB'));
const out = [];
out.push('<!-- generated by 03_train/lab/cli/ladder-tables.js; do not hand-edit -->');
out.push('');
out.push(`# Ladder: ${rows.length} named versions x ${rows[0].games} games on ${rows[0].seedSet}`);
out.push('');
out.push('## Game score');
out.push('');
out.push('| agent | median | q1 | q3 | mean | max | min | run |');
out.push('|---|---:|---:|---:|---:|---:|---:|---|');
for (const r of rows) {
  out.push(`| ${r.agent} | ${fmt(round(r.score.median, 0))} | ${fmt(round(r.score.q1, 0))} `
    + `| ${fmt(round(r.score.q3, 0))} | ${fmt(round(r.score.mean, 0))} | ${fmt(r.score.max)} `
    + `| ${fmt(r.score.min)} | ${r.runId} |`);
}
out.push('');
out.push('## Survival and chains');
out.push('');
out.push('| agent | blocks median | blocks max | longest chain median | longest chain max |');
out.push('|---|---:|---:|---:|---:|');
for (const r of rows) {
  out.push(`| ${r.agent} | ${fmt(r.blocksPlaced.median)} | ${fmt(r.blocksPlaced.max)} `
    + `| ${fmt(r.longestChain.median)} | ${fmt(r.longestChain.max)} |`);
}
out.push('');
out.push('## Max tile reached, share of games');
out.push('');
const allTiles = [...new Set(rows.flatMap((r) => r.maxTile.histogram.map((h) => h.value)))].sort((a, b) => a - b);
out.push(`| agent | ${allTiles.map(fmt).join(' | ')} |`);
out.push(`|---|${allTiles.map(() => '---:').join('|')}|`);
for (const r of rows) {
  const byValue = new Map(r.maxTile.histogram.map((h) => [h.value, h.share]));
  out.push(`| ${r.agent} | ${allTiles.map((t) => {
    const share = byValue.get(t);
    return share ? `${(share * 100).toFixed(1)}%` : '.';
  }).join(' | ')} |`);
}
out.push('');
out.push('## Merges by group size, all games');
out.push('');
const sizes = [...new Set(rows.flatMap((r) => Object.keys(r.mergeCounts)))].sort((a, b) => a - b);
out.push(`| agent | ${sizes.map((s) => `size ${s}`).join(' | ')} |`);
out.push(`|---|${sizes.map(() => '---:').join('|')}|`);
for (const r of rows) {
  out.push(`| ${r.agent} | ${sizes.map((s) => fmt(r.mergeCounts[s] ?? 0)).join(' | ')} |`);
}
out.push('');

const outDir = args.out ?? '.';
mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, 'ladder.md'), `${out.join('\n')}\n`);
writeFileSync(path.join(outDir, 'ladder.json'), `${JSON.stringify({
  seedSet: rows[0].seedSet, games: rows[0].games, rows,
}, null, 2)}\n`);
console.log(`ladder over ${rows.length} runs written to ${outDir}`);
